import Image from "next/image";

import Container from "./../Container";

function Card({ title, imgSrc, imgAlt, children }) {
  return (
    <div className="max-w-[280px] flex flex-col items-center justify-start gap-2">
      <Image src={imgSrc} alt={imgAlt} width={72} height={72} />
      <p className="font-medium text-lg">{title}</p>
      <p className="text-[hsl(0,_0%,_30%)] text-center">{children}</p>
    </div>
  );
}

export default function Guide() {
  return (
    <div className="p-4 bg-[#146EB4]/10">
      <Container className="flex flex-row items-start justify-center gap-8 flex-wrap">
        <Card title="Search" imgSrc="/icons/layout.svg" imgAlt="icon layout">
          Simply add a keyword or a term related to your business in the slogan
          maker search box. Wait for the magic to happen.
        </Card>
        <Card title="Select" imgSrc="/icons/cursor.svg" imgAlt="icon cursor">
          Choose from thousands of options generated by the slogan maker that
          fit your needs.
        </Card>
        <Card title="Stand out" imgSrc="/icons/ups.svg" imgAlt="icon ups">
          Congrats on your new slogan. {"It's "}time to win the world!
        </Card>
      </Container>
    </div>
  );
}
